[colors]
transparent_background_colors = true

[env]
TERM = "xterm-256color"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

# [window]
# opacity = 0.9
