;;; kbd-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from kbd-mode.el

(autoload 'kbd-mode "kbd-mode" "\
Major mode for editing `.kbd' files.

For details, see `https://github.com/kmonad/kmonad'.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.kbd\\'" . kbd-mode))
(autoload 'kbd-mode-demo-mode "kbd-mode" "\
Toggle kmonad demo mode.

This is a minor mode, in which users can test their
configurations.

This is a minor mode.  If called interactively, toggle the
`Kbd-Mode-Demo mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `kbd-mode-demo-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'kbd-mode-start-demo "kbd-mode" "\
Try the current configuration in a demo buffer.
Use `kbd-mode-stop-demo' to stop the demo.  If the configuration
file has errors, the demo will not start and an error buffer will
be shown instead." t)
(register-definition-prefixes "kbd-mode" '("kbd-mode-"))

;;; End of scraped data

(provide 'kbd-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kbd-mode-autoloads.el ends here
